package command;

public enum CommandName {
    WRONG_REQUEST,
    SIGN_IN,
    INDEX,
    FIND_BY_TYPE,
    SIGN_OUT,
    SHOW_ORDER_ADMIN,
    SHOW_ORDER_WAITER,
    ADD_PRODUCT_BASKET,
    REMOVE_PRODUCT_BASKET,
    EDIT_PROFILE,
    CLOSE_ORDER,
    WAITER_PROFILE,
    DELETE_PRODUCT,
    ADD_PRODUCT,
    SHOW_WAITER,
    SHOW_PRODUCT,
    SHOW_ADMIN
}
