package command;

public enum CommandName {
    WRONG_REQUEST,
    SIGN_IN,
    SIGN_UP,
    INDEX,
    CHANGE_LOCALE,
    FIND_BY_TYPE,
    SIGN_OUT,
    SHOW_ORDER_ADMIN,
    SHOW_ORDER_WAITER,
    ADD_PRODUCT_BASKET,
    REMOVE_PRODUCT_BASKET,
    CLOSE_ORDER,
    CLIENT_PROFILE,
    DELETE_PRODUCT,
    ADD_PRODUCT,
    SHOW_CLIENT,
    BAN_CLIENT,
    SHOW_ADMIN
}
